@echo off
REM Sprint 5.2 Commit: Unified Demo Seed

git commit -m "feat(sprint5.2): Unified demo seed with 9 threads across 3 sectors" -m "Sprint 5.2 'Unified Demo Seed' implementation:" -m "" -m "A) Unified Demo Seed Service (services/demo_seed.py):" -m "   - Renamed seed_demo_data() → seed_demo_all()" -m "   - Creates 9 threads total across 3 sectors:" -m "     * 3 salon threads (demo_salon_001..003) with 10 messages" -m "     * 3 store threads (demo_store_001..003) with 11 messages" -m "     * 3 clinic threads (demo_clinic_001..003) with 12 messages" -m "   - Total: 33 messages in realistic Jordan/Palestine dialect" -m "   - 6 leads (2 per sector) linked to threads" -m "   - 9 tasks (3 per sector): 1 overdue, 1 today, 1 tomorrow" -m "   - 15 saved replies (5 per sector) in Arabic + English" -m "   - Idempotent check for all demo thread patterns" -m "   - Helper functions: _seed_salon(), _seed_store(), _seed_clinic()" -m "" -m "B) Dashboard Integration (ui_components/dashboard_view.py):" -m "   - Updated to call seed_demo_all()" -m "   - Added demo_error i18n key for error messages" -m "   - Shows replies count in success message" -m "   - Navigates to ops page after seeding (go_to('ops'))" -m "" -m "C) Inbox Empty State (ui_components/inbox_view.py):" -m "   - Updated to call seed_demo_all()" -m "   - Maintains Sprint 5.2 comment markers" -m "" -m "D) i18n Keys (utils/translations.py):" -m "   - Added demo_error key in EN/AR/FR" -m "   - Updated Sprint 5.1 → 5.2 comment markers" -m "" -m "E) Tests (tests/sprint5_2_smoke.py):" -m "   - Test 1: Unified demo seed (verifies 9 threads, 6 leads, 9 tasks, 15 replies)" -m "   - Test 2: Idempotency check (second call returns skipped=True)" -m "   - Test 3: Sector coverage (3 threads per sector)" -m "   - All 3/3 tests pass ✅" -m "" -m "Demo Data Structure:" -m "   Salon: Hair appointments, bridal makeup, service complaints" -m "   Store: Cleaning products, delivery inquiries, order delays" -m "   Clinic: Dental cleaning, laser treatments, wait time complaints" -m "   All messages in authentic Jordanian/Palestinian Arabic" -m "" -m "Files Changed:" -m "   ~ services/demo_seed.py (+267 lines, -107 lines)" -m "   + tests/sprint5_2_smoke.py (133 lines)" -m "   ~ ui_components/dashboard_view.py (+7 lines, -4 lines)" -m "   ~ ui_components/inbox_view.py (+2 lines, -2 lines)" -m "   ~ utils/translations.py (+4 lines, -1 line)" -m "" -m "Impact:" -m "   - One unified demo seed instead of sector selector" -m "   - Comprehensive demo data across 3 business types" -m "   - User sees value immediately (ops dashboard)" -m "   - Minimal diffs, no new dependencies" -m "   - All text via i18n" -m "" -m "Test Output:" -m "   🚀 Sprint 5.2 Smoke Tests: Unified Demo Seed" -m "   🧪 Test 1: ✅ 9 threads, 33 messages, 6 leads, 9 tasks, 15 replies" -m "   🧪 Test 2: ✅ Idempotency verified" -m "   🧪 Test 3: ✅ Sector coverage: 3 salon, 3 store, 3 clinic" -m "   📊 Results: 3/3 tests passed" -m "" -m "Sprint 5.2 Complete ✅"

echo.
echo Commit created successfully!
echo.
pause
