@echo off
REM Sprint 5.1 Commit: Pilot Ready Features

git commit -m "feat(sprint5.1): Add pilot-ready features with demo data and cross-page navigation" -m "Sprint 5.1 'Pilot Ready' implementation with minimal diffs:" -m "" -m "A) Demo Seed Service (services/demo_seed.py - 163 lines):" -m "   - seed_demo_data() function with idempotent checks" -m "   - Creates 3 demo threads (instagram/whatsapp/facebook)" -m "   - Inserts 8 realistic beauty salon messages" -m "   - Links 2 leads to threads (Lina, Ahmed)" -m "   - Creates 3 tasks (overdue/today/tomorrow)" -m "   - Seeds 5 saved replies (EN + AR)" -m "   - Checks for existing demo-% threads before inserting" -m "   - Returns counts dict or {skipped: True} if data exists" -m "" -m "B) Dashboard Integration (ui_components/dashboard_view.py):" -m "   - Added demo seed button in col3 quick actions" -m "   - Button text: '🧪 Load Demo Inbox' via i18n" -m "   - Shows success with counts or info if data exists" -m "   - Triggers rerun on successful load" -m "" -m "C) Cross-Page Navigation (ui_components/inbox_view.py):" -m "   - Added auto-select logic for selected_thread_id" -m "   - Search → Inbox navigation now auto-opens thread" -m "   - Preserves session state across page transitions" -m "" -m "D) Bulk Actions Empty State (ui_components/inbox_view.py):" -m "   - Shows helpful hint when no threads exist" -m "   - Offers demo seed button in empty state" -m "   - Guides users to load demo data" -m "" -m "E) i18n Keys (utils/translations.py):" -m "   - load_demo (EN/AR/FR)" -m "   - demo_exists (EN/AR/FR)" -m "   - demo_loaded (EN/AR/FR)" -m "   - bulk_empty_hint (EN/AR/FR)" -m "   - All text via get_text() for consistency" -m "" -m "F) Tests (tests/sprint5_1_smoke.py - 189 lines):" -m "   - Test demo seed data loading (counts verification)" -m "   - Test idempotency (second call skips)" -m "   - Test thread count after seeding" -m "   - Test search query simulation" -m "   - Test cross-page selection simulation" -m "   - All 5/5 tests pass" -m "" -m "Schema Fixes:" -m "   - Fixed leads table column: source → source_platform" -m "   - Fixed tasks table columns: task_type/status/lead_id → type/completed/related_lead_id" -m "   - Aligned with CRM store schema" -m "" -m "Files Changed (7 files, 404+ lines):" -m "   + services/demo_seed.py (163 lines)" -m "   + tests/sprint5_1_smoke.py (189 lines)" -m "   ~ ui_components/dashboard_view.py (+13)" -m "   ~ ui_components/inbox_view.py (+20)" -m "   ~ utils/translations.py (+18)" -m "" -m "Impact:" -m "   - Solves cold-start problem for new users" -m "   - One-click demo data loading from dashboard or bulk actions" -m "   - Realistic beauty salon conversation data" -m "   - Cross-page selection works seamlessly" -m "   - All features tested and verified" -m "" -m "Sprint 5.1 Complete ✅"

echo.
echo Commit created successfully!
echo.
pause
