@echo off
REM Sprint 5.3 Commit: Demo Management UI Controls

git commit -m "feat(sprint5.3): Add demo management controls (Clear/Regenerate)" -m "Sprint 5.3 'Demo Management' implementation:" -m "" -m "A) Demo Management Functions (services/demo_seed.py):" -m "   - Added clear_demo_all() - deletes all demo data safely" -m "     * Deletes messages (FK to threads)" -m "     * Deletes leads linked to demo threads" -m "     * Deletes tasks linked to demo threads" -m "     * Deletes demo saved replies (salon/store/clinic tags)" -m "     * Deletes demo threads last" -m "     * Returns: {cleared, threads_deleted, messages_deleted, leads_deleted, tasks_deleted, replies_deleted}" -m "   - Added seed_demo_regenerate() - clear then seed fresh" -m "     * Returns: {cleared: {...}, seeded: {...}}" -m "   - Added _is_demo_id() helper function" -m "   - Updated seed_demo_all() return format:" -m "     * Now includes: created, reason fields" -m "     * Better structured response" -m "" -m "B) Dashboard 3-Button UI (ui_components/dashboard_view.py):" -m "   - Split col3 into 3 sub-columns (col3a/col3b/col3c)" -m "   - Button 1 (🧪): Load Demo - calls seed_demo_all()" -m "   - Button 2 (🔄): Regenerate - calls seed_demo_regenerate()" -m "   - Button 3 (🗑️): Clear - calls clear_demo_all()" -m "   - Navigation: Seed/Regenerate → go_to('ops'), Clear → stay" -m "   - All messages use i18n keys" -m "" -m "C) Inbox View (ui_components/inbox_view.py):" -m "   - Updated Sprint 5.2 → 5.3 marker" -m "   - Keeps single Load Demo button in empty state" -m "" -m "D) i18n Keys (utils/translations.py):" -m "   - Added demo_cleared (EN/AR/FR)" -m "   - Added demo_regenerated (EN/AR/FR)" -m "   - Added regenerate_demo button label (EN/AR/FR)" -m "   - Added clear_demo button label (EN/AR/FR)" -m "   - Updated Sprint 5.2 → 5.3 markers" -m "" -m "E) Tests (tests/sprint5_3_smoke.py - 192 lines):" -m "   - Test 1: Clear demo data" -m "   - Test 2: Seed after clear" -m "   - Test 3: Idempotency check" -m "   - Test 4: Regenerate (clear + seed)" -m "   - Test 5: Sector coverage verification" -m "   - All 5/5 tests pass ✅" -m "" -m "Files Changed (5 files, +404/-23):" -m "   ~ services/demo_seed.py (+153 lines)" -m "   + tests/sprint5_3_smoke.py (192 lines)" -m "   ~ ui_components/dashboard_view.py (+62/-23)" -m "   ~ ui_components/inbox_view.py (+1/-1)" -m "   ~ utils/translations.py (+18/-5)" -m "" -m "Test Results:" -m "   Sprint 5.3: 5/5 tests passed ✅" -m "   Sprint 5.2: 3/3 tests passed ✅ (regression check)" -m "" -m "Impact:" -m "   - Users can now regenerate demo data without restarting" -m "   - Clear demo data to start from clean state" -m "   - Improved error handling with structured responses" -m "   - All operations are idempotent and safe" -m "   - Referential integrity maintained" -m "" -m "Sprint 5.3 Complete ✅"

echo.
echo Commit created successfully!
echo.
pause
